services:
  - type: web
    name: glasschat
    env: python
    plan: free         
    region: oregon
    repo: https://github.com/GlassChat/glasschat
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
